export const naacCriterionCatalog = [
    {
        criteriaCode: "C1",
        criteriaName: "Curricular Aspects",
        summary:
            "Programs, departments, and curricular breadth captured from institutional academic structures.",
    },
    {
        criteriaCode: "C2",
        criteriaName: "Teaching, Learning and Evaluation",
        summary:
            "Faculty teaching capacity, student base, and approved annual academic reporting indicators.",
    },
    {
        criteriaCode: "C3",
        criteriaName: "Research, Innovations and Extension",
        summary:
            "Institutional research output and extension activity aggregated from PBAS, AQAR, publication, and project modules.",
    },
    {
        criteriaCode: "C4",
        criteriaName: "Infrastructure and Learning Resources",
        summary:
            "Organizational learning-resource readiness and institutional support structures available for accreditation reporting.",
    },
    {
        criteriaCode: "C5",
        criteriaName: "Student Support and Progression",
        summary:
            "Student progression indicators aggregated from the active student placement and internship records.",
    },
    {
        criteriaCode: "C6",
        criteriaName: "Governance, Leadership and Management",
        summary:
            "Leadership and quality-governance readiness synthesized from users, responsibilities, and operational notices.",
    },
    {
        criteriaCode: "C7",
        criteriaName: "Institutional Values and Best Practices",
        summary:
            "Institutional values, best practices, and outreach indicators built from AQAR quality narratives and collaboration footprints.",
    },
] as const;

export type NaacCriteriaCode = (typeof naacCriterionCatalog)[number]["criteriaCode"];

export const naacMetricCatalog = [
    {
        criteriaCode: "C1",
        criteriaName: "Curricular Aspects",
        tableName: "Program",
        fieldReference: "programsOffered",
        label: "Programs offered",
        sourceType: "Program",
        sourceLabel: "Academic programs",
        defaultWeightage: 30,
        valueType: "count",
    },
    {
        criteriaCode: "C1",
        criteriaName: "Curricular Aspects",
        tableName: "Organization",
        fieldReference: "departmentsReporting",
        label: "Departments reporting",
        sourceType: "Organization",
        sourceLabel: "Departments",
        defaultWeightage: 25,
        valueType: "count",
    },
    {
        criteriaCode: "C1",
        criteriaName: "Curricular Aspects",
        tableName: "Organization",
        fieldReference: "collegesReporting",
        label: "Colleges reporting",
        sourceType: "Organization",
        sourceLabel: "Colleges",
        defaultWeightage: 20,
        valueType: "count",
    },
    {
        criteriaCode: "C1",
        criteriaName: "Curricular Aspects",
        tableName: "FacultyTeachingLoad",
        fieldReference: "averageCoursesPerFaculty",
        label: "Average courses per faculty",
        sourceType: "FacultyTeachingLoad",
        sourceLabel: "Average teaching distribution",
        defaultWeightage: 25,
        valueType: "number",
    },
    {
        criteriaCode: "C2",
        criteriaName: "Teaching, Learning and Evaluation",
        tableName: "User",
        fieldReference: "totalFaculty",
        label: "Total faculty",
        sourceType: "User",
        sourceLabel: "Active faculty",
        defaultWeightage: 25,
        valueType: "count",
    },
    {
        criteriaCode: "C2",
        criteriaName: "Teaching, Learning and Evaluation",
        tableName: "User",
        fieldReference: "totalStudents",
        label: "Total students",
        sourceType: "User",
        sourceLabel: "Student user base",
        defaultWeightage: 25,
        valueType: "count",
    },
    {
        criteriaCode: "C2",
        criteriaName: "Teaching, Learning and Evaluation",
        tableName: "Student",
        fieldReference: "activeStudents",
        label: "Active students",
        sourceType: "Student",
        sourceLabel: "Active student records",
        defaultWeightage: 20,
        valueType: "count",
    },
    {
        criteriaCode: "C2",
        criteriaName: "Teaching, Learning and Evaluation",
        tableName: "FacultyPbasForm",
        fieldReference: "approvedPbasReports",
        label: "Approved PBAS reports",
        sourceType: "PBAS",
        sourceLabel: "PBAS reports linked",
        defaultWeightage: 30,
        valueType: "count",
    },
    {
        criteriaCode: "C3",
        criteriaName: "Research, Innovations and Extension",
        tableName: "Publication",
        fieldReference: "facultyPublications",
        label: "Research publications",
        sourceType: "Publication",
        sourceLabel: "Research publications",
        defaultWeightage: 30,
        valueType: "count",
    },
    {
        criteriaCode: "C3",
        criteriaName: "Research, Innovations and Extension",
        tableName: "Publication",
        fieldReference: "booksAndChapters",
        label: "Books and chapters",
        sourceType: "Publication",
        sourceLabel: "Books and chapters",
        defaultWeightage: 20,
        valueType: "count",
    },
    {
        criteriaCode: "C3",
        criteriaName: "Research, Innovations and Extension",
        tableName: "Project",
        fieldReference: "projectsAndMoUs",
        label: "Projects and MoUs",
        sourceType: "Project",
        sourceLabel: "Projects and MoUs",
        defaultWeightage: 25,
        valueType: "count",
    },
    {
        criteriaCode: "C3",
        criteriaName: "Research, Innovations and Extension",
        tableName: "AqarApplication",
        fieldReference: "facultyAqarContributions",
        label: "Faculty AQAR contributions",
        sourceType: "AQARContribution",
        sourceLabel: "Faculty AQAR entries",
        defaultWeightage: 25,
        valueType: "count",
    },
    {
        criteriaCode: "C4",
        criteriaName: "Infrastructure and Learning Resources",
        tableName: "Organization",
        fieldReference: "universities",
        label: "Universities",
        sourceType: "Organization",
        sourceLabel: "Universities",
        defaultWeightage: 25,
        valueType: "count",
    },
    {
        criteriaCode: "C4",
        criteriaName: "Infrastructure and Learning Resources",
        tableName: "Organization",
        fieldReference: "colleges",
        label: "Colleges",
        sourceType: "Organization",
        sourceLabel: "Colleges",
        defaultWeightage: 25,
        valueType: "count",
    },
    {
        criteriaCode: "C4",
        criteriaName: "Infrastructure and Learning Resources",
        tableName: "Organization",
        fieldReference: "departments",
        label: "Departments",
        sourceType: "Organization",
        sourceLabel: "Departments",
        defaultWeightage: 20,
        valueType: "count",
    },
    {
        criteriaCode: "C4",
        criteriaName: "Infrastructure and Learning Resources",
        tableName: "MasterData",
        fieldReference: "officesAndSupportUnits",
        label: "Offices and support units",
        sourceType: "MasterData",
        sourceLabel: "Administrative offices",
        defaultWeightage: 30,
        valueType: "count",
    },
    {
        criteriaCode: "C5",
        criteriaName: "Student Support and Progression",
        tableName: "Placement",
        fieldReference: "placements",
        label: "Placements",
        sourceType: "Placement",
        sourceLabel: "Placement records",
        defaultWeightage: 35,
        valueType: "count",
    },
    {
        criteriaCode: "C5",
        criteriaName: "Student Support and Progression",
        tableName: "Internship",
        fieldReference: "internships",
        label: "Internships",
        sourceType: "Internship",
        sourceLabel: "Internship records",
        defaultWeightage: 35,
        valueType: "count",
    },
    {
        criteriaCode: "C5",
        criteriaName: "Student Support and Progression",
        tableName: "Student",
        fieldReference: "activeStudents",
        label: "Active students",
        sourceType: "Student",
        sourceLabel: "Active student records",
        defaultWeightage: 30,
        valueType: "count",
    },
    {
        criteriaCode: "C6",
        criteriaName: "Governance, Leadership and Management",
        tableName: "User",
        fieldReference: "adminAndLeadershipUsers",
        label: "Leadership roles",
        sourceType: "User",
        sourceLabel: "Leadership roles",
        defaultWeightage: 25,
        valueType: "count",
    },
    {
        criteriaCode: "C6",
        criteriaName: "Governance, Leadership and Management",
        tableName: "Faculty",
        fieldReference: "administrativeResponsibilities",
        label: "Administrative responsibilities",
        sourceType: "FacultyProfile",
        sourceLabel: "Administrative responsibilities",
        defaultWeightage: 30,
        valueType: "count",
    },
    {
        criteriaCode: "C6",
        criteriaName: "Governance, Leadership and Management",
        tableName: "SystemMisc",
        fieldReference: "activeSystemUpdates",
        label: "Active system updates",
        sourceType: "SystemMisc",
        sourceLabel: "Operational notices",
        defaultWeightage: 20,
        valueType: "count",
    },
    {
        criteriaCode: "C6",
        criteriaName: "Governance, Leadership and Management",
        tableName: "CasApplication",
        fieldReference: "casApplications",
        label: "CAS applications",
        sourceType: "CAS",
        sourceLabel: "CAS applications",
        defaultWeightage: 25,
        valueType: "count",
    },
    {
        criteriaCode: "C7",
        criteriaName: "Institutional Values and Best Practices",
        tableName: "FacultyQualification",
        fieldReference: "qualifiedFacultyProfiles",
        label: "Qualified faculty profiles",
        sourceType: "FacultyProfile",
        sourceLabel: "Faculty with qualification records",
        defaultWeightage: 30,
        valueType: "count",
    },
    {
        criteriaCode: "C7",
        criteriaName: "Institutional Values and Best Practices",
        tableName: "Project",
        fieldReference: "collaborations",
        label: "Collaborations",
        sourceType: "Project",
        sourceLabel: "Collaborations",
        defaultWeightage: 25,
        valueType: "count",
    },
    {
        criteriaCode: "C7",
        criteriaName: "Institutional Values and Best Practices",
        tableName: "AqarApplication",
        fieldReference: "facultyAqarNarratives",
        label: "Faculty AQAR narratives",
        sourceType: "AQARContribution",
        sourceLabel: "AQAR narratives",
        defaultWeightage: 20,
        valueType: "count",
    },
    {
        criteriaCode: "C7",
        criteriaName: "Institutional Values and Best Practices",
        tableName: "StudentProgression",
        fieldReference: "outreachIndicators",
        label: "Outreach indicators",
        sourceType: "StudentProgression",
        sourceLabel: "Outreach indicators",
        defaultWeightage: 25,
        valueType: "count",
    },
] as const;

export type NaacMetricCatalogEntry = (typeof naacMetricCatalog)[number];

export function getNaacCriterionMeta(criteriaCode: string) {
    return (
        naacCriterionCatalog.find((item) => item.criteriaCode === criteriaCode) ??
        null
    );
}

export function getNaacMetricMeta(
    tableName: string,
    fieldReference: string
): NaacMetricCatalogEntry | null {
    return (
        naacMetricCatalog.find(
            (item) =>
                item.tableName === tableName &&
                item.fieldReference === fieldReference
        ) ?? null
    );
}

export const defaultNaacCriteriaMappings = naacMetricCatalog.map((item) => ({
    criteriaCode: item.criteriaCode,
    criteriaName: item.criteriaName,
    tableName: item.tableName,
    fieldReference: item.fieldReference,
    weightage: item.defaultWeightage,
}));
