import type { PbasCategoryCode } from "@/models/core/pbas-category-master";

export const PBAS_CATEGORIES: Array<{
    categoryCode: PbasCategoryCode;
    categoryName: string;
    maxScore: number;
    displayOrder: number;
}> = [
    { categoryCode: "A", categoryName: "Teaching and Learning", maxScore: 100, displayOrder: 1 },
    { categoryCode: "B", categoryName: "Research and Academic Contribution", maxScore: 120, displayOrder: 2 },
    { categoryCode: "C", categoryName: "Extension and Institutional Responsibilities", maxScore: 80, displayOrder: 3 },
];

export const PBAS_INDICATORS: Array<{
    categoryCode: PbasCategoryCode;
    indicatorCode: string;
    indicatorName: string;
    description?: string;
    maxScore: number;
    naacCriteriaCode?: string;
}> = [
    {
        categoryCode: "A",
        indicatorCode: "A1_TEACHING_LOAD",
        indicatorName: "Lectures / Classes Taken",
        description: "Teaching workload including lectures and tutorials handled.",
        maxScore: 30,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "A",
        indicatorCode: "A2_COURSE_PREP",
        indicatorName: "Course Preparation & Delivery",
        description: "Course preparation, lesson plan design, and delivery quality.",
        maxScore: 20,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "A",
        indicatorCode: "A3_MENTORING",
        indicatorName: "Mentoring & Student Support",
        description: "Mentoring, counseling, and academic guidance.",
        maxScore: 20,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "A",
        indicatorCode: "A4_LAB_SUPERVISION",
        indicatorName: "Lab / Practical Supervision",
        description: "Laboratory, studio, or practical supervision.",
        maxScore: 15,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "A",
        indicatorCode: "A5_INNOVATIVE_PEDAGOGY",
        indicatorName: "Innovative Pedagogy",
        description: "Innovative teaching practices and ICT integration.",
        maxScore: 15,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "A",
        indicatorCode: "A6_CURRICULUM_DEV",
        indicatorName: "Curriculum Design & Enrichment",
        description: "Curriculum development, syllabus design, and enrichment activities.",
        maxScore: 15,
        naacCriteriaCode: "CR1",
    },
    {
        categoryCode: "A",
        indicatorCode: "A7_ECONTENT_DEVELOPMENT",
        indicatorName: "E-Content / Course Material",
        description: "Preparation of course material, e-content, and learning resources.",
        maxScore: 10,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "A",
        indicatorCode: "A8_STUDENT_FEEDBACK",
        indicatorName: "Student Feedback & Mentoring Outcomes",
        description: "Feedback utilization and student outcome improvements.",
        maxScore: 10,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "A",
        indicatorCode: "A9_ASSESSMENT_INNOVATION",
        indicatorName: "Assessment & Evaluation Innovations",
        description: "Innovative evaluation methods, CO/PO mapping, and assessment design.",
        maxScore: 10,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "B",
        indicatorCode: "B1_RESEARCH_PAPERS",
        indicatorName: "Research Publications",
        description: "Journal publications, indexing, and quality.",
        maxScore: 40,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "B",
        indicatorCode: "B2_BOOKS_CHAPTERS",
        indicatorName: "Books / Chapters",
        description: "Books, edited volumes, and chapters.",
        maxScore: 20,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "B",
        indicatorCode: "B3_PATENTS",
        indicatorName: "Patents",
        description: "Filed, published, or granted patents.",
        maxScore: 20,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "B",
        indicatorCode: "B4_CONFERENCES",
        indicatorName: "Conference Contributions",
        description: "Conference presentations and participation.",
        maxScore: 20,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "B",
        indicatorCode: "B5_PROJECTS",
        indicatorName: "Research Projects / Grants",
        description: "Externally or internally funded projects.",
        maxScore: 20,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "B",
        indicatorCode: "B6_RESEARCH_GUIDANCE",
        indicatorName: "Research Guidance / PhD Supervision",
        description: "PhD, MPhil, and research scholar guidance outcomes.",
        maxScore: 20,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "B",
        indicatorCode: "B7_CONSULTANCY",
        indicatorName: "Consultancy & Industry Collaboration",
        description: "Consultancy projects and industry collaboration outcomes.",
        maxScore: 15,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "B",
        indicatorCode: "B8_ECONTENT",
        indicatorName: "E-Content / LMS Contributions",
        description: "MOOCs, SWAYAM, LMS content, and digital courseware contributions.",
        maxScore: 15,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "B",
        indicatorCode: "B9_MOOC_COMPLETION",
        indicatorName: "MOOC / SWAYAM Completion",
        description: "Faculty completion of MOOCs or SWAYAM courses.",
        maxScore: 10,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "B",
        indicatorCode: "B10_AWARDS",
        indicatorName: "Awards & Recognitions",
        description: "Research awards, fellowships, and recognitions.",
        maxScore: 10,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "B",
        indicatorCode: "B11_RESEARCH_IMPACT",
        indicatorName: "Research Impact / Citations",
        description: "Citation impact, h-index, and research influence metrics.",
        maxScore: 10,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "B",
        indicatorCode: "B12_EDITORIAL_REVIEW",
        indicatorName: "Editorial / Review Contributions",
        description: "Editorial board, peer review, and academic review roles.",
        maxScore: 10,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "C",
        indicatorCode: "C1_ADMIN_ROLES",
        indicatorName: "Committee / Administrative Roles",
        description: "Department, institute, or university level roles.",
        maxScore: 20,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "C",
        indicatorCode: "C2_EXAM_DUTIES",
        indicatorName: "Examination Duties",
        description: "Invigilation, evaluation, and exam coordination.",
        maxScore: 15,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "C",
        indicatorCode: "C3_STUDENT_GUIDANCE",
        indicatorName: "Student Guidance",
        description: "Project supervision, internships, and guidance.",
        maxScore: 15,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "C",
        indicatorCode: "C4_EXTENSION",
        indicatorName: "Extension / Outreach",
        description: "NSS, NCC, outreach, and community engagement.",
        maxScore: 15,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "C",
        indicatorCode: "C5_FDP_WORKSHOPS",
        indicatorName: "FDP / Workshops",
        description: "Faculty development programs and workshops.",
        maxScore: 15,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "C",
        indicatorCode: "C6_PROFESSIONAL_BODY",
        indicatorName: "Professional Body Membership",
        description: "Membership in professional bodies and learned societies.",
        maxScore: 10,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "C",
        indicatorCode: "C7_COMMUNITY_SERVICE",
        indicatorName: "Community Service",
        description: "Community service, social outreach, and civic engagement.",
        maxScore: 10,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "C",
        indicatorCode: "C8_OUTREACH_PROGRAMS",
        indicatorName: "Outreach Programs & Camps",
        description: "Outreach camps, awareness programs, and institutional outreach.",
        maxScore: 10,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "C",
        indicatorCode: "C9_RESOURCE_PERSON",
        indicatorName: "Resource Person / Invited Talks",
        description: "Invited talks, resource person roles, and expert lectures.",
        maxScore: 10,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "C",
        indicatorCode: "C10_GOVERNANCE_ROLE",
        indicatorName: "Institutional Governance",
        description: "Institutional governance, policy, and accreditation roles.",
        maxScore: 10,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "A",
        indicatorCode: "A_TOTAL",
        indicatorName: "Teaching Activities Total",
        description: "Computed total for PBAS teaching activities.",
        maxScore: 100,
        naacCriteriaCode: "CR2",
    },
    {
        categoryCode: "B",
        indicatorCode: "B_TOTAL",
        indicatorName: "Research Contribution Total",
        description: "Computed total for PBAS research and academic contributions.",
        maxScore: 120,
        naacCriteriaCode: "CR3",
    },
    {
        categoryCode: "C",
        indicatorCode: "C_TOTAL",
        indicatorName: "Institutional Responsibility Total",
        description: "Computed total for PBAS institutional responsibilities and extension.",
        maxScore: 80,
        naacCriteriaCode: "CR7",
    },
    {
        categoryCode: "C",
        indicatorCode: "API_TOTAL",
        indicatorName: "Overall API Total",
        description: "Computed overall API total score for the PBAS form.",
        maxScore: 300,
        naacCriteriaCode: "CR2",
    },
];
